package hu.webarticum.inno.paperdatabase.abstractgenerator.model.keyword;

import java.util.Arrays;

import hu.webarticum.inno.paperdatabase.abstractgenerator.model.Keyword;
import hu.webarticum.inno.paperdatabase.abstractgenerator.model.PlaceholderType;

public enum KeywordEnum {
    
    AI("Artifical Intelligence",
            typeCase(PlaceholderType.AREA,
                    new String[] { "plucking", "marthrement", "ketorny-harness" },
                    new String[] { "[A-Z]{3}\\d\\-(mache|hitxe)" }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "terribloxon", "horronity", "pruff" },
                    new String[] { "[XY]\\-crash" }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "analyzer", "LLM", "evolutionary technique" },
                    new String[] { "[A-Z]{3}-analysis" }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "model", "robot" },
                    new String[] { "NLV-\\d{3}" }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "speak", "listen" },
                    new String[] { "[XYZ]-match" })),
    
    ALGORITHMS("Algorithms",
            typeCase(PlaceholderType.AREA,
                    new String[] { "calculation", "doxrting" },
                    new String[] { "p[aei]fking" }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "EVIL", "DEVIL" },
                    new String[] { "X\\d{2}\\-ouch" }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "algorithm", "method", "analiser strategy" },
                    new String[] { "[A-Z]{3}\\-method" }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "thing", "item" },
                    new String[] { "[ABC]\\-agent" }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "calculate", "move" },
                    new String[] { "[A-Z]\\d\\-create" })),

    ASTRO_INSTR("Astronomical Instrumentation",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    ASTROPHYSICS("Astrophysics",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    CATALYSIS("Catalysis",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    COMPILERS("Compilers",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    COMPUTER_VIS("Computer Vision",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    CONDENSED_MAT("Condensed Matter",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    CONTROL_THEORY("Control Theory",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    CRYPTOGRAPHY("Cryptography",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    DATA_PRIVACY("Data Privacy",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    DATA_STRUCTS("Data Structures",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    DATABASES("Databases",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    DISTRIBUTED("Distributed Systems",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    ELECTROCHEM("Electrochemistry",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    EMBEDDED("Embedded Systems",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    EPIDEMIOLOGY("Epidemiology Modeling",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    EXOPLANETS("Exoplanets",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    VERIFICATION("Formal Verification",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    GENOMICS("Genomics",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    GRAPH_THEORY("Graph Theory",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    ML("Machine Learning",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    MATERIALS_MOD("Materials Modeling",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    MED_IMAGING("Medical Imaging",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    MOLECULAR_MOD("Molecular Modeling",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    NLP("Natural Language Processing",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    NEUROSCIENCE("Neuroscience",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    NUM_ANALYSIS("Numerical Analysis",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    OPTIMIZATION("Optimization",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    OS("Operating Systems",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    PROBABILITY("Probability Theory",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    QC("Quantum Computing",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    RELIABILITY("Reliability Engineering",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    ROBOTICS("Robotics",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    SIGNAL_PROC("Signal Processing",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    SPECTROSCOPY("Spectroscopy",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    SYS_BIOLOGY("Systems Biology",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    T_SERIES("Time-Series Analysis",
            typeCase(PlaceholderType.AREA,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.DIFFICULTY,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.METHOD,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.ITEM,
                    new String[] { "lorem" },
                    new String[] {  }),
            typeCase(PlaceholderType.VERB,
                    new String[] { "lorem" },
                    new String[] {  })),

    ;
    
    private final Keyword keyword;
    
    private KeywordEnum(String longname, PlaceholderTypeWordsSpec... placeholderTypeWordsSpecs) {
        this.keyword = new DefaultKeyword(longname, Arrays.asList(placeholderTypeWordsSpecs));
    }
    
    public Keyword keyword() {
        return keyword;
    }
    
    private static PlaceholderTypeWordsSpec typeCase(PlaceholderType placeholderType, String[] fixedStrings, String[] regexes) {
        return new PlaceholderTypeWordsSpec(placeholderType, fixedStrings, regexes);
    }

}
