micronaut:
  application:
    name: holodb-jpa-demo
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: 'jdbc:holodb:jpa:///mockdata'
    username: ''
    password: ''
    driverClassName: 'hu.webarticum.holodb.jpa.JpaMetamodelDriver'
jpa:
  default:
    properties:
      hibernate:
        show_sql: false
